import { challengeCatalog, lessonCatalog, libraryCatalog } from "@/lib/corpus";
import { ACHIEVEMENTS } from "@/lib/achievements";
import { PROMPTS, TOPICS } from "@/lib/community";
import { GUIDE_META } from "@/lib/guides";
import { WORLDS } from "@/lib/worlds";

// GET /api/dev/seed-sql — development only. Emits the catalog seed (supabase/migrations/*_seed_catalog.sql) from the same
// functions the app renders from, so the database never drifts from the datasets. Regenerate after content changes:
//   curl -s localhost:3000/api/dev/seed-sql > supabase/migrations/20260923120100_seed_catalog.sql
// Every statement is an upsert: re-running it updates the catalog and never deletes user data.

const q = (s: string | null | undefined) => (s == null ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const arr = (a: readonly string[]) => (a.length ? `array[${a.map(q).join(", ")}]::text[]` : "'{}'::text[]");
const json = (x: unknown) => `${q(JSON.stringify(x))}::jsonb`;
// Traditional single-author attributions, as the Guides describe them (anthologies are left empty).
const AUTHORS: Record<string, string[]> = { tirukkural: ["Thiruvalluvar"], tolkappiyam: ["Tolkappiyar"], silappatikaram: ["Ilango Adigal"], manimekalai: ["Cīttalai Cāttaṉār"] };
const title = (id: string) => `${id[0].toUpperCase()}${id.slice(1)} World`;

function upsert(table: string, key: string, rows: Record<string, string>[]) {
  if (!rows.length) return "";
  const cols = Object.keys(rows[0]);
  const values = rows.map((r) => `  (${cols.map((c) => r[c]).join(", ")})`).join(",\n");
  const set = cols.filter((c) => c !== key).map((c) => `${c} = excluded.${c}`).join(", ");
  return `insert into public.${table} (${cols.join(", ")}) values\n${values}\non conflict (${key}) do update set ${set};\n\n`;
}

export function GET() {
  if (process.env.NODE_ENV !== "development") return new Response("Not found", { status: 404 });
  const lessons = lessonCatalog();
  const challenges = challengeCatalog();
  const worldOfLayer = (layer: string) => ({ Didactic: "thirukkural", Sangam: "sangam", Bhakti: "bhakti", Spiritual: "bhakti", Epic: "history", Grammar: "grammar" })[layer] ?? null;

  let sql = `-- Catalog seed, generated by GET /api/dev/seed-sql from the app's own data. Idempotent (upserts only).\n\n`;
  sql += upsert("worlds", "id", WORLDS.map((w, i) => ({
    id: q(w.id), title: q(title(w.id)), subtitle: q(w.sub), description: q(w.about), period: q(w.span), color: q(w.color),
    image: q(`/worlds/${w.id}.webp`), position: String(i), active: "true", metadata: json({ i18n_key: w.key }),
  })));
  sql += upsert("lessons", "id", lessons.map((l, i) => ({
    id: q(l.id), world_id: q(l.world), title: q(l.title), summary: q(l.summary), level: q(l.level), image: q(l.image),
    source: q(l.source), steps: json(l.steps), position: String(i), active: "true", metadata: json({ step_count: l.steps.length }),
  })));
  sql += upsert("challenges", "id", challenges.map((c, i) => ({
    id: q(c.id), world_id: q(c.world), lesson_id: "null", kind: q(c.kind), title: q(c.title), summary: q(c.summary), image: q(c.image),
    round_size: String(c.round), question_count: String(c.pool.length), xp_per_correct: "15", source: q(c.source), position: String(i),
    active: "true", metadata: json({}),
  })));
  sql += upsert("guides", "id", GUIDE_META.map((g) => ({
    id: q(g.id), name: q(g.name), name_ta: q(g.ta), category: q(g.category), era: q(g.era), sort_order: String(g.order), tags: arr(g.tags),
    world_id: q(g.world), glyph: q(g.glyph), image: q(g.image), bio: q(g.bio), poet_names: arr(g.poet ?? []), active: "true",
  })));
  sql += upsert("library_texts", "slug", libraryCatalog().map((t) => ({
    slug: q(t.slug), name: q(t.name), name_ta: q(t.ta), layer: q(t.layer), period: q(t.period), description: q(t.description), unit: q(t.unit),
    item_count: String(t.count), world_id: q(worldOfLayer(t.layer)), authors: arr(AUTHORS[t.slug] ?? []), // anthologies have many poets; per-verse attribution stays in the corpus
    reference: q(t.slug === "tirukkural" ? "datasets/Thirukkural.pdf" : t.slug === "tolkappiyam" ? "Project Madurai" : "Sentamizh corpus (Apache-2.0)"),
    status: q("available"), metadata: json({}),
  })));
  sql += upsert("achievements", "id", ACHIEVEMENTS.map((a, i) => ({
    id: q(a.id), title: q(a.title), description: q(a.description), goal: String(a.goal), xp: String(a.xp), diamonds: String(a.diamonds), position: String(i),
  })));
  sql += upsert("community_topics", "id", TOPICS.map((t, i) => ({ id: q(t.id), label: q(t.label), position: String(i) })));
  sql += upsert("community_posts", "slug", PROMPTS.map((p) => ({
    slug: q(p.id), author_id: "null", is_official: "true", topic_id: q(p.topic), title: q(p.title), body: q(p.body), tags: arr(p.tags),
    ref_label: q(p.ref?.label), ref_href: q(p.ref?.href), created_at: q(p.at),
  })));
  sql += `-- Profiles for anyone who signed up before this schema existed (the trigger covers everyone after).
insert into public.profiles (id, email, full_name, avatar_url, provider)
select u.id, u.email,
       nullif(left(coalesce(u.raw_user_meta_data ->> 'full_name', u.raw_user_meta_data ->> 'name'), 80), ''),
       coalesce(u.raw_user_meta_data ->> 'avatar_url', u.raw_user_meta_data ->> 'picture'),
       coalesce(u.raw_app_meta_data ->> 'provider', 'email')
from auth.users u
on conflict (id) do nothing;
insert into public.user_stats (user_id) select id from public.profiles on conflict (user_id) do nothing;
`;
  return new Response(sql, { headers: { "Content-Type": "text/plain; charset=utf-8" } });
}
