"use client";

import { useEffect, useState } from "react";
import { Bot, Loader2 } from "lucide-react";

type Ai = { word: string; transliteration: string; meanings: string[]; partOfSpeech: string; example: string; explanation: string };
type State = { status: "loading" } | { status: "ok"; ai: Ai } | { status: "error" } | { status: "verified" };

// Unknown-word card: the verified vocabulary had nothing, so ask the server's Groq fallback — and say so plainly.
export default function AiMeaning({ word }: { word: string }) {
  const [s, setS] = useState<State>({ status: "loading" });
  useEffect(() => {
    const ctl = new AbortController(); // parent remounts this per word (key), so state starts at loading
    fetch(`/api/meaning?w=${encodeURIComponent(word)}`, { signal: ctl.signal })
      .then(async (r) => {
        const j = await r.json();
        setS(j.ai ? { status: "ok", ai: j.ai } : j.verified ? { status: "verified" } : { status: "error" });
      })
      .catch((e) => { if (e.name !== "AbortError") setS({ status: "error" }); });
    return () => ctl.abort();
  }, [word]);
  if (s.status === "verified") return null;

  return (
    <section className="word-card ai" aria-live="polite">
      <header className="wc-head">
        <h2 lang="ta">{word}</h2>
        {s.status === "ok" && s.ai.transliteration && <span className="wc-tr">{s.ai.transliteration}</span>}
        <span className="wc-status ai"><Bot size={14} /> AI-Assisted Meaning</span>
      </header>
      <p className="wc-warn">This word is not currently verified in the Solveli corpus.</p>

      <h3>Meaning</h3>
      {s.status === "loading" && <p className="sp-state"><Loader2 size={16} className="spin" /> Looking up an AI-assisted meaning…</p>}
      {s.status === "error" && (
        <p className="wc-warn">This word is not currently verified in the Solveli corpus, and an AI-assisted meaning is temporarily unavailable.</p>
      )}
      {s.status === "ok" && (
        <>
          {s.ai.meanings.length > 0 ? <p className="wc-meaning">{s.ai.meanings.join(" · ")}</p> : <p className="sub">No meaning could be suggested.</p>}
          {s.ai.partOfSpeech && <p className="wc-row"><span>Part of speech</span>{s.ai.partOfSpeech}</p>}
          {s.ai.example && <p className="wc-row"><span>Example (AI-written)</span><i lang="ta">{s.ai.example}</i></p>}
          {s.ai.explanation && <p className="wc-row"><span>Explanation</span>{s.ai.explanation}</p>}
        </>
      )}

      <h3>Literary Evidence</h3>
      <p className="sub">Not available in the current verified Solveli corpus.</p>
      <p className="wc-row"><span>Status</span><b className="wc-status ai">Not verified</b></p>
      <p className="fine">AI-generated by Groq on request. It is an explanation, not evidence — Solveli cites only passages it holds.</p>
    </section>
  );
}
